server:
  port: 8888

spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lovezhh1314
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8

  profiles:
    active: test

